name: Backend Deployment

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"  # Adjust the version as needed

      - name: Install npm dependencies
        run: npm install

      - name: Build application
        run: npm run dist:service

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.6"  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
        
      - name: deploy tfstate resource config
        working-directory: backendterraform
        run: terraform apply -auto-approve

      - name: deploy 
        working-directory: terraform
        run: terraform apply -auto-approve
    
   
