name: frontend deployment
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init